class User < ActiveRecord::Base
    has_secure_password
    # validate :val_pass


    # def authenticate(password)
    #     # Salts generated by generate_salt are always 29 chars long.
    #     salt = password_digest[0..28]
    #     hashed = BCrypt::Engine::hash_secret(password, salt)
    #     return nil unless (salt + hashed) == self.password_digest
    #   end

end
